apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: medrecapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: medrecapi
        version: v1
    spec:
      containers:
      - name: medrecapi
        image: medrec_image:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: ocirsecretname
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: medrecapi
  labels:
    app: medrecapi
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: medrecapi
